# Generated by Django 4.2.6 on 2023-10-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
