# Generated by Django 4.2.6 on 2023-10-29 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_session_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allow_player_addition', models.BooleanField(default=True)),
                ('maximum_players', models.PositiveSmallIntegerField(default=11)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.session')),
            ],
        ),
        migrations.CreateModel(
            name='Standby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.session')),
            ],
        ),
    ]
